### PR TITLE
added stagehand generator (for dart)

### PR DESCRIPTION
**Pull request by kasperpeulen**
added stagehand generator (for dart)

### CODE REVIEW

**Comment by gdi2290** [comment]
can you make another pull-request to change the format (after you merge this)
```
### Angular 2 Generators
* Node.js
  * Yeoman
    * [swirlycheetah/generator-angular2](https://github.com/swirlycheetah/generator-angular2)
  * Slush
    * [TheVelourFog/slush-angular2](https://github.com/TheVelourFog/slush-angular2)
* Dart
  * Stagehand
    * [kasperpeulen/stagehand](https://github.com/kasperpeulen/stagehand)

```

**Comment by kasperpeulen** [comment]
okay done that :)

**Comment by gdi2290** [comment]
thanks! you have write permission so merge at will :+1:

**Comment by kasperpeulen** [comment]
ah awesome! @gdi2290

**Pull request merged**
