### PR TITLE
docs: added ng-seed/universal, ng-seed/spa, components and docs

### PR DESCRIPTION
**Pull request by fulls1z3**

### CODE REVIEW

**Comment by fulls1z3** [comment]
Thanks @rolandjitsu 👍

**Comment by rolandjitsu** [comment]
@fulls1z3 should I just close the prev. PR?

**Comment by fulls1z3** [comment]
@rolandjitsu the previous one is pointing to the `gh-pages` branch, while this one points to the `master` branch. It seems that prev PR should be merged too.

**Comment by rolandjitsu** [comment]
Oh, just noticed. But `gh-pages` is the default, so PRs to master are unnecessary as far as I can see (hasn't been updated in months/years).

**Comment by fulls1z3** [comment]
I saw, and I thought about syncing all contents with `gh-pages`. In that case I should create PR's for `gh-pages` branch only.

**Pull request merged**
