### PR TITLE
added ngx-auth-firebaseui, ngx-material-pages, ngx-material-password-…

### PR DESCRIPTION
**Pull request by AnthonyNahas**
added some new angular ui components

### CODE REVIEW

**Comment by rolandjitsu** [comment]
Please fix the current conflicts and we can merge this PR.

**Comment by rolandjitsu** [comment]
Closing this due to inactivity.

**Comment by AnthonyNahas** [comment]
@rolandjitsu sorry for the late response. I've only added few lines to the markdown file. Which conflicts should I fix to let the ci works ?

**Comment by rolandjitsu** [comment]
Just rebase you branch from upstream, should be ok.

**Comment by AnthonyNahas** [comment]
done! I've just updated the readme

**Pull request merged**
