### PR TITLE
Add Babel plugins

### PR DESCRIPTION
**Pull request by shuhei**
Adding babel plugins for Angular 2.

### CODE REVIEW

**Comment by shuhei** [comment]
Is it OK to make PR to `gh-pages` branch? Should I do so to `master` instead?

**Comment by gdi2290** [comment]
:+1:

**Comment by gdi2290** [comment]
yeah gh-pages is where everything should go. I'll delete master soon

**Comment by shuhei** [comment]
Got it. How about the `index.html`? It seems be synced with REAME.md by some tooling but I couldn't find it. Can I just leave it?

**Comment by gdi2290** [comment]
you can leave index.html I'll update it once a week

**Comment by shuhei** [comment]
I see thanks!

**Pull request merged**
