### PR TITLE
Adding the book Angular 2 in Action

### PR DESCRIPTION
**Pull request by rafaelaudy**
Adding the book Angular 2 in Action

### CODE REVIEW

**Comment by gdi2290** [comment]
Lol Angular 2 is not even released yet

**Comment by rafaelaudy** [comment]
I thought that was ok, since there is one book there that is also not released :)

[Angular 2 Development with TypeScript](https://www.manning.com/books/angular-2-development-with-typescript)

**Comment by gdi2290** [comment]
can you rebase

**Comment by rafaelaudy** [comment]
Sure, sorry :) 
Done!

**Comment by gdi2290** [comment]
thanks!

**Comment by gdi2290** [comment]
I'll add you to the repo

**Comment by rafaelaudy** [comment]
Thanks :) I'll keep an eye for the good stuff out there.

**Pull request merged**
