### PR TITLE
Update ES6 content

### PR DESCRIPTION
**Pull request by shuhei**
- Create a Traceur section that was mixed with Babel
- Add a Babel plunker
- Github -> GitHub

### CODE REVIEW

**Comment by rolandjitsu** [comment]
@shuhei it would be nice to specify that the setup at [babel-angular2-app](https://github.com/shuhei/babel-angular2-app/blob/master/gulpfile.babel.js) is actually using [Browserify](http://browserify.org/) to run the app, but probably not necessary.

**Comment by rolandjitsu** [comment]
@shuhei nevermind, I just updated the description with this [commit](https://github.com/angular-class/awesome-angular2/commit/9a6528bb1817e9eae662c60687b28653adde50b9).

**Comment by gdi2290** [comment]
ya @shuhei could you update your repository description to mention browserify.

**Comment by shuhei** [comment]
@rolandjitsu Thanks!

@gdi2290 Did it. https://github.com/shuhei/babel-angular2-app

I didn't include Browserify because it was not the point. The repo was actually using Webpack when it had to transpile angular2 es6 files in node_modules. But you guys are right. It is using Browserify now.

**Pull request merged**
