### PR TITLE
Added Bit under "components"

### PR DESCRIPTION
**Pull request by jonisar**
Added Bit - a virtual repository for exporting, storing, maintaining, managing, finding and reusing components from any context across applications.

### CODE REVIEW

**Comment by rolandjitsu** [comment]
@jonisar how does this relate to Angular? I mean, you placed it under the components section, yet this is more of a tool than a component if I'm correct.

**Comment by jonisar** [comment]
Bit lets you export, manage and reuse Angular components across applications (quick and efficient).
You can create and manage a set of reusable Angular components and still maintain and use them individually from any application. Material2 (and more) components will also be added soon.

I added it under components since it enables work with components, but yeah- it's more of a tool so if there'e a better place that's fine! I just didn't find one

**Comment by rolandjitsu** [comment]
I think you should create a new entry, similar to [Haxe](https://github.com/AngularClass/awesome-angular#angular-2-in-haxe). Don't forget to add it to the table of contents.

**Comment by jonisar** [comment]
K no problem

**Pull request closed without merging**
